name: CI/CD Tests

on:
    push:
        branches:
            - main
        tags:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    tests_run:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                python:
                    - "3.9"
                    - "3.10"
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Python ${{ matrix.python }}
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install tox tox-gh-actions

            -   name: Install Graphviz on Linux
                if: runner.os == 'Linux'
                run: sudo apt-get install -y graphviz
            -   name: Install Graphviz on macOS
                if: runner.os == 'macOS'
                run: brew install graphviz
            -   name: Install Graphviz on Windows
                if: runner.os == 'Windows'
                run: choco install graphviz -y

            -   name: Project internals test build
                run: "tox"
